FROM golang:1.7.3
WORKDIR /happy-birthday-c9s
RUN go get -u github.com/mbndr/figlet4go/...
COPY seafood.go .
RUN GOOS=linux go build -o seafood .

FROM alpine:latest  
WORKDIR /root/
COPY --from=0 /happy-birthday-c9s .
CMD ["./seafood"]  